Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,20 +25,25 @@ jobs:
 
       - name: Install Chrome WebDriver
         run: |
-          LATEST_CHROMEDRIVER_VERSION=124.0.6367.78
-          curl -sS -o chromedriver_linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/${LATEST_CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip"
-          sudo unzip chromedriver_linux64.zip -d /usr/local/bin
-          sudo rm chromedriver_linux64.zip
+         LATEST_CHROMEDRIVER_VERSION=124.0.6367.78
+         curl -sS -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver-linux64.zip"
+         sudo unzip chromedriver_linux64.zip -d /usr/local/bin
+         sudo rm chromedriver_linux64.zip
 
-      - name: Set up chromedriver
-        run: |
-          sudo rm /usr/local/bin/chromedriver || true
-          if [ ! -f "/usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell" ]; then
-          echo "chrome-headless-shell not found."
-          exit 1
-          fi
-          sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
-          sudo chmod +x /usr/local/bin/chromedriver
+         if [ ! -f "/usr/local/bin/chromedriver" ]; then
+         echo "chromedriver not found."
+         exit 1
+         fi
+
+         sudo rm /usr/local/bin/chromedriver || true
+
+         # 注意：这步可能不需要，因为 chromedriver 已经解压到了 /usr/local/bin/
+         # sudo ln -sf /usr/local/bin/chromedriver /usr/local/bin/chromedriver
+
+         sudo chmod +x /usr/local/bin/chromedriver
+
+         /usr/local/bin/chromedriver --version
+    
       - name: Run hunan
         run: python ${{ github.workspace }}/hnyuan.py
                                
