Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,14 +26,19 @@ jobs:
       - name: Install Chrome WebDriver
         run: |
           LATEST_CHROMEDRIVER_VERSION=124.0.6367.78
-          curl -sS -o chromedriver_linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.78/linux64/chromedriver-linux64.zip"
+          curl -sS -o chromedriver_linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/${LATEST_CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip"
           sudo unzip chromedriver_linux64.zip -d /usr/local/bin
-          rm chromedriver_linux64.zip
-      - name: Set chromedriver path
+          sudo rm chromedriver_linux64.zip
+
+      - name: Set up chromedriver
         run: |
+          sudo rm /usr/local/bin/chromedriver || true
+          if [ ! -f "/usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell" ]; then
+          echo "chrome-headless-shell not found."
+          exit 1
+          fi
           sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
           sudo chmod +x /usr/local/bin/chromedriver
-
       - name: Run hunan
         run: python ${{ github.workspace }}/hnyuan.py
                                
